### ISSUE TITLE
p-t训练时报错"save_prefixencoder"参数未定义

### ISSUE THREAD

**Issue by wenyv** [CSHaitao/ChatGLM_mutli_gpu_tuning#1]
您好，使用您的代码在p-tuning时出现报错 TypeError: Trainer.__init__() got an unexpected keyword argument 'save_prefixencoder'，检查trainer代码也确实没有定义这个参数，原版的chatglm自己的trainer定义了这个参数[trainer定义了这个参数](https://github.com/THUDM/ChatGLM-6B/blob/main/ptuning/trainer.py#LL320C16-L320C16) 在finetune_ptuning.py中是否也应当使用这个自定义的trainer呢？

**Comment by CSHaitao** [comment]
是的，应该使用这个自定义的trainer，非常感谢。我会更新一下代码
